### ISSUE TITLE
libs missing from service.radarr-9.2.0.34.zip ?

### ISSUE THREAD

**Issue by KilljoyTXinWA** [thoradia/LibreELEC.tv#93] opened 2020-09-26 02:37 UTC
I'm not an expert by any means, but I compare  

https://raw.githubusercontent.com/thoradia/thoradia/master/9.2.0/Generic/x86_64/service.radarr/service.radarr-9.2.0.34.zip and 
https://raw.githubusercontent.com/thoradia/thoradia/master/9.2.0/Generic/x86_64/service.radarr/service.radarr-9.2.0.26.zip 

and they are very dissimilar. Is there a reason for this? 

Just got clear from the mono 33% install issue on my new libreelec install and ran into this issue. 
Installed 9.2.0.26 from the Zip, and turned off auto-update, seems to be stable now. 

Thanks for your work, I appreciate it.

**Comment by thoradia** [comment] 2020-09-26 11:23
Thank you for the feedback
The issue is fixed with revision 35 of the Radarr add-on

From revision 34 on, the Radarr add-on is a bootstrap that downloads the latest release of Radarr Aphrodite when it is (re)installed
The add-on uses .Net Core, except on RPi (0, 1) where it still uses Mono because .Net Core is not available

**Comment by thoradia** [comment] 2020-10-06 06:28
Deemed solved

**Closed as completed by thoradia** 2020-10-06 06:28 UTC
