### ISSUE TITLE
Standalone version of Jackett is now available - Mono not required

### ISSUE THREAD

**Issue by soyxan** [thoradia/LibreELEC.tv#60] opened 2019-05-22 07:28 UTC
When running latest version of Jackett from your repository, it shows the following message:

```
Standalone version of Jackett is now available - Mono not required 
To upgrade to the standalone version of Jackett, click here for install instructions. Upgrading is straight forward, simply install the standalone version and your indexers/configuration will carry over. Benefits include: increased performance, improved stability and no dependency on Mono.
```
The "here" link goes to:
https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above

The update process from the UI will not work as this is a different release, so I have followed the instructions and downloaded manually the bianries, but I get the following error when trying to run this standalone version of Jackett from the command-line:

```
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.CreateAppDomainManager()
   at System.AppDomain.Setup(System.Object)
Aborted
```

Please can you move to this "standalone version", considering the advantages estated in the message?

Thanks for your great work!

**Comment by thoradia** [comment] 2019-05-22 08:35
Standalone Jackett is architecture dependent (aarch64, arm or x86_64) and ships .Net runtime without system dependencies. Moving to standalone Jackett therefore requires repackaging the add-on, which is work in progress.

This work was delayed by the fact that auto-update of standalone Jackett uses a lot of memory and would hang LibreELEC on memory constrained systems such as Raspberry Pi. Enabling swap on such systems solves the problem.

Therefore, expect standalone Jackett in the coming weeks.

**Comment by soyxan** [comment] 2019-05-22 08:55
BTW, I am using it in RPi3. This "swap" enabling will be needed in order to run this standalone version? Will be enabled automatically when installing the addon?

**Comment by thoradia** [comment] 2019-05-22 09:39
You have to enable swap yourself, see [here](https://forum.libreelec.tv/thread/2707-thoradia-add-ons/?postID=116554#post116554)
Enabling swap is recommended when auto-updating Jackett, Radarr and Sonarr

I found another issue with standalone Jackett: it does not run on Raspberry Pi 1 and 0

**Comment by soyxan** [comment] 2019-05-22 12:41
Ok, I will wait for your new version of the add-on. Thanks!

**Comment by soyxan** [comment] 2019-05-22 12:43
Sorry for the open/close. I will wait for the new version of the add-on. Thanks!

**Comment by thoradia** [comment] 2019-05-23 18:01
Jackett is now standalone, except for RPi 0 and 1 where Jackett still runs with Mono

**Comment by soyxan** [comment] 2019-05-23 19:00
Do I have to do anything in order to move to this new standalone version or is it enough to wait for the auto add-on update from Kodi?

**Comment by rafuz** [comment] 2019-05-24 10:45
From the last reboot of libreelec my jacket instance does not start anymore.
The last line in the log refers to the updater starting.
I have to reinstall the plugin to get it working with the "standalone" version?

EDIT: seems that the service.jackett.service can't find the binary in /storage/.kodi/addon/service.jackett/jackett/jackett and actually it does not exists

**Comment by soyxan** [comment] 2019-05-24 11:34
Same situation here, the addon was auto-updated (by Kodi) to 9.0.39 from 9.0.38 (non stand-alone) and now the web UI is not accesible.
I can confirm that the binary pointed by @rafuz does not exist.

**Comment by edjalmobf** [comment] 2019-05-24 13:26
Actualy we have a bug here!
After the Thoradia update Jackett start, but after jackett update by itself make Jackett break.
I don't know why but when Jackett update, it delete the folder /bin (or change it location) and so it does not start.
So to run Jackett until Thoradia fix this, go to Jackett add-on UI and click in update, also disable Jackett update in Jackett UI to prevent this happend again.

@thoradia 
You can remove `Requires=tools.mono.service` of Jackett's systemd service.
.NET add-on is not necessary? (Seems not since Jackett start without it!)
I noticed that the Jackett variant is Binaries.LinuxARM32.tar.gz but RPi 3b is ARM64, right?! Why use ARM32 version?

Jackett update seems to be a problem yet. My RPi is running for 4 days (thanks swap + MemoryHigh), when I clicked in update the system freezes, or maybe freezes is not the best word, because I actualy can access the system, but the acess was very very slow while the upgrade process was running.
But fix this and we can see better and report this to Jackett developers.

EDIT: weird thing! I forget to disable auto update of Jackett and it updated, but after update is running fine. I don't know why this, but for the record: before I update Jackett manually clicking in "Check for updates".

**Comment by thoradia** [comment] 2019-05-25 08:43
I successfully updated Jackett from 0.11.361 to 0.11.364 and 0.11.365 by clicking on Check for updates in the user interface. I will wait for Jackett to auto-update to 0.11.375 to see if I can reproduce the issue.

Issue is a [known Jackett issue](https://github.com/Jackett/Jackett/issues/5208).

If you encounter the auto-update issue, please provide the output of `journalctl -u service.jackett`

@edjalmobf 
tools.mono requirement has already been removed from service.jackett, see [here](https://github.com/thoradia/thoradia/commit/2854f5db364f3b2abfb46b5e6249c0d2553046c9).
Standalone Jackett ships .Net Core runtime and does therefore not require the .Net Core Runtime add-on.
ARCH of LibreELEC for RPi and RPi2 is arm (ARM32). ARCH for LibreELEC/CoreELEC add-ons is arm (ARM32).

**Comment by edjalmobf** [comment] 2019-05-25 14:39
Today had another update of Jackett (v0.11.375). Again I clicked in check for updates and Jackett break.
`journalctl -u service.jackett` show this https://pastebin.com/XaZnmZr9
and `systemctl status service.jackett.service` show this https://pastebin.com/qv9kxjMc
`updater.txt` (shows manually and automatically updates, for what I saw): https://pastebin.com/K8b7HBu5
I think If I don't click in check for updates and let Jackett update automatically this is will not happen.

`Requires=tools.mono.service` and `After=tools.mono.serviceis` still [here](https://github.com/thoradia/LibreELEC.tv/blob/9.0/packages/thoradia/addons/jackett/source/system.d/service.jackett.service)

EDIT: after read this Jackett issue thread I think this is because out of memory. 
@soyxan, @rafuz e @thoradia you are using swap too?

**Comment by thoradia** [comment] 2019-05-25 17:31
[Reverting to Jackett for Mono, which runs fine](https://en.wiktionary.org/wiki/if_it_ain%27t_broke,_don%27t_fix_it)

**Closed as completed by thoradia** 2019-05-25 17:31 UTC

**Comment by edjalmobf** [comment] 2019-05-28 18:57
I hope you can switch again when this bug be fixed!
.NET version is much better than mono version.
When you said you was reverting I disabled the add-on update and kept .NET version.
Look at my Jackett status. Current I use it to only search, not rss sync.
jackett status (this is, of course, with no search in the moment, but you can see that now it can release the memory usage)
![jackett status](https://user-images.githubusercontent.com/42322017/58503767-a1ec3980-815f-11e9-8d8e-6f761447f2eb.png)
This is beautiful ^^
I current can't test the update because I have afraid of loose it, if it breaks it.
Hope this is fix quickly!

**Comment by soyxan** [comment] 2019-05-30 11:15
> @soyxan, @rafuz e @thoradia you are using swap too?

Yes I am using swap.

**Comment by edjalmobf** [comment] 2019-05-30 11:24
But now I don't really now if this issue is for lack of memory!
In Jackett thread, users say that is not because that.
The Jackett new update broke my .Net version, so I went back to Mono.
Lets wait this update issue be fixed and so Thoradia can back to .Net version.

**Comment by peskdale** [comment] 2019-11-21 00:09
The issue with the Jackett update process has now been resolved - https://github.com/Jackett/Jackett/issues/5208

Any chance Thoradia will switch back to the standalone version of Jackett?
