### ISSUE TITLE
Couchpotato startup issue for 8.1/Odroid_C2/aarch64/

### ISSUE THREAD

**Issue by mjktfw** [thoradia/LibreELEC.tv#7] opened 2016-12-22 21:04 UTC
Hey, couchpotato does not start up for 8.1/Odroid_C2/aarch64/ on LibreELEC 7.90.009
sonarr, transmission, sabnzbd work well.
Error log remains empty, but logfile loops with the info below:

> 12-22 21:52:07 INFO [0m[  couchpotato.core.loader] Loaded core: _core[0m
12-22 21:52:07 INFO [0m[  couchpotato.core.loader] Loaded core: clientscript[0m
12-22 21:52:07 INFO [0m[  couchpotato.core.loader] Loaded core: desktop[0m
12-22 21:52:07 INFO [0m[  couchpotato.core.loader] Loaded core: downloader[0m
12-22 21:52:07 INFO [0m[  couchpotato.core.loader] Loaded core: scheduler[0m
12-22 21:52:07 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.github.com/repos/CouchPotato/CouchPotatoServer/commits?per_page=1&sha=master, data: [][0m
12-22 21:52:07 INFO [0m[  couchpotato.core.loader] Loaded core: updater[0m
12-22 21:52:07 INFO [0m[  couchpotato.core.loader] Loaded plugin: automation[0m
12-22 21:52:07 INFO [0m[  couchpotato.core.loader] Loaded plugin: browser[0m
12-22 21:52:08 INFO [0m[  couchpotato.core.loader] Loaded plugin: category[0m
12-22 21:52:08 INFO [0m[  couchpotato.core.loader] Loaded plugin: custom[0m
12-22 21:52:08 INFO [0m[  couchpotato.core.loader] Loaded plugin: dashboard[0m
12-22 21:52:08 INFO [0m[tato.core._base.scheduler] Scheduling file.cleanup, interval: hours = 24, minutes = 0, seconds = 0[0m
12-22 21:52:08 INFO [0m[  couchpotato.core.loader] Loaded plugin: file[0m
12-22 21:52:08 INFO [0m[  couchpotato.core.loader] Loaded plugin: log[0m
12-22 21:52:08 INFO [0m[  couchpotato.core.loader] Loaded plugin: manage[0m
12-22 21:52:08 INFO [0m[  couchpotato.core.loader] Loaded plugin: profile[0m
12-22 21:52:08 INFO [0m[  couchpotato.core.loader] Loaded plugin: quality[0m
12-22 21:52:08 INFO [0m[tato.core._base.scheduler] Scheduling movie.clean_releases, interval: hours = 12, minutes = 0, seconds = 0[0m
12-22 21:52:08 INFO [0m[  couchpotato.core.loader] Loaded plugin: release[0m
12-22 21:52:08 INFO [0m[  couchpotato.core.loader] Loaded plugin: renamer[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded core: _core[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded core: clientscript[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded core: desktop[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded core: downloader[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded core: scheduler[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded core: updater[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded plugin: automation[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded plugin: browser[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded plugin: category[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded plugin: custom[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded plugin: dashboard[0m
12-22 21:52:14 INFO [0m[tato.core._base.scheduler] Scheduling file.cleanup, interval: hours = 24, minutes = 0, seconds = 0[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded plugin: file[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded plugin: log[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded plugin: manage[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded plugin: profile[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded plugin: quality[0m
12-22 21:52:14 INFO [0m[tato.core._base.scheduler] Scheduling movie.clean_releases, interval: hours = 12, minutes = 0, seconds = 0[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded plugin: release[0m
12-22 21:52:14 INFO [0m[  couchpotato.core.loader] Loaded plugin: renamer[0m

**Comment by thoradia** [comment] 2016-12-22 23:45
Thank you for reporting.
I have no system to test.
All I can do is rebuild latest CouchPotato against latest LibreELEC.

**Comment by mlipscombe** [comment] 2017-01-07 08:38
The problem is that it has Python bytecode files included in the zip, which are causing a segfault.  Removing all files ending in *.pyo fixes the problem and allows it to start without problem.

**Comment by thoradia** [comment] 2017-01-07 10:04
Thank you for the feedback, @mlipscombe 
I will update the add-ons as soon as possible.

**Comment by thoradia** [comment] 2017-01-09 14:46
Reopen issue. Removing .pyo files breaks LXML and SSL

**Comment by thoradia** [comment] 2017-01-10 07:27
I removed strip_lto from Python packages. This should fix couchpotato segfault on aarch64 without breaking LXML/SSL. Please report outcome.

**Comment by thoradia** [comment] 2017-01-10 13:30
@mjktfw @mlipscombe please report

**Comment by thoradia** [comment] 2017-01-25 00:47
No feedback, no problem: closing

**Closed by thoradia** 2017-01-25 00:47 UTC
